{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Period\", \"Sales\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "Period-Sales",
        "fromColumn": "Period",
        "fromTable": "Sales",
        "toColumn": "Period",
        "toTable": "Period"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Period",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b5900fe-38f9-433e-acc9-200358e6c21e",
            "sourceColumn": "Period",
            "summarizeBy": "none"
          },
          {
            "name": "SortOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "749aad06-ed44-456b-be46-5167c22d4fe0",
            "sourceColumn": "SortOrder",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "64d09beb-5664-4caa-9fd1-dfbb4684b54d",
        "partitions": [
          {
            "name": "Period",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8g1xUdJRMlSK1YlWCgSzjcDsSDDbWCk2FgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Period = _t, SortOrder = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Period\", type text}, {\"SortOrder\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88481f55-1e71-412d-8ea8-49e6e682bf37",
            "sourceColumn": "Period",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a9e5052-2fd1-4ea4-9a16-204d377be902",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "RevenueValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "lineageTag": "7cff79d5-de12-454d-bae6-c362710c54f3",
            "sourceColumn": "RevenueValue",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "674d0cda-0b73-462f-9216-c21985fac386",
        "measures": [
          {
            "name": "Revenue",
            "expression": "SUM('Sales'[RevenueValue])",
            "formatString": "#,0.0",
            "lineageTag": "f8d92f5d-85b2-4d30-bbb9-dbfb71a85749"
          }
        ],
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8g1xUdJR8ssvKskA0oZGFnomSrE6MPHg/FKwuKW5nhmScHhqcQlItYmxniFYOBDFFGNLQz0jJHGYKcYGRnoWSOJQY0yAlpqDhSNRHWMKVG+JJAEzx9DQAubMSBT3mJkb65kqxcYCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Period = _t, Region = _t, RevenueValue = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Period\", type text}, {\"Region\", type text}, {\"RevenueValue\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}